# ========== SERVER ==========
# usa a porta dinâmica fornecida pelo Railway (fallback 8080 localmente)
server.port=${PORT:8080}

# ========== DATASOURCE ==========
# substitui pelos nomes de variáveis que o Railway já fornece (sem underscore)
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ========== JPA / HIBERNATE ==========
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.sql.init.mode=ALWAYS

# ========== SESSIONS JDBC ==========
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never




